### ISSUE TITLE
Any example of TCP/HTTP  server?

### ISSUE THREAD

**Issue by rohitjoshi** [capsule-rs/capsule#101]
## Describe what you'd like to see/use?
I would love to TCP/HTTP server example similar to https://github.com/ansyun/dpdk-ans/tree/master/examples/http_server

**Comment by zeeshanlakhani** [comment]
Hey @rohitjoshi,

Projects like dpdk-ans have built-out their own userspace TCP/IP stack using DPDK, akin to [F-stack](http://www.f-stack.org/) or [mTCP](https://github.com/mtcp-stack/mtcp). It would be interesting to see if someone could build a TCP/IP stack atop Capsule, but it's not the direction we want to take at this time. Instead, we've been focused mainly on packet-processing itself and abstractions around it. 

Thanks.

**Comment by qiujiangkun** [comment]
I've implemented a http example with capsule and smoltcp. However, the code is private and for commercial use. If you are interested, I can give you some ideas and snippets, though.

**Comment by skeggse** [comment]
@qiujiangkun I was just looking at doing this, actually! If you've got any hints, I'd be grateful!

**Comment by JakkuSakura** [comment]
> @qiujiangkun I was just looking at doing this, actually! If you've got any hints, I'd be grateful!

What I do is to create my own `[Async]Write/Read` with `smoltcp` for the TCP layer, and spin up a thread to process requests such as `TcpSocket::connect` and `TcpSocket::listen`. On top of that, `async-tls` and `hyper` can be used. You might find memory pooled `Vec<u8>` useful in transferring data between threads. `Arc<AtomicCell<TcpState>>` is also helpful.

https://github.com/smoltcp-rs/smoltcp/issues/474

My use case is mostly for low latency real-world multithreaded clients. If you just want the simplest implementation, it's fine to use raw `rustls` and process HTTP on your own, without building a socket with Rust's `[Async]Read/Write` or using existing crates
