### ISSUE TITLE
Add `hacktoberfest` label

### ISSUE THREAD

**Issue by BrittanyIstenes** [capsule-rs/capsule#113]
Add Hacktoberfest tag at the top of your repo October 1, 2020 and create `hacktoberfest label in issues.

**Comment by zeeshanlakhani** [comment]
🌮 . Will do as we approach the date.

**Comment by Anita-ihuman** [comment]
Is this issue still available?
can I tackle it?

**Comment by zeeshanlakhani** [comment]
@BrittanyIstenes added tag and label.
