### ISSUE TITLE
Keep track of rust-core regex issue around memleak

### ISSUE THREAD

**Issue by zeeshanlakhani** [capsule-rs/capsule#122]
Based on https://github.com/capsule-rs/capsule/pull/120#issuecomment-768483707 and https://github.com/rust-lang/regex/issues/739. We should remain aware of this around the time for updating rust/nightly.

**Comment by drunkirishcoder** [comment]
It's been [fixed](https://github.com/Amanieu/thread_local-rs/commit/a44b836f90e0317d256ed1dd4cff745feff285ea).
