### ISSUE TITLE
Invalid discord invitation

### ISSUE THREAD

**Issue by qiujiangkun** [capsule-rs/capsule#135]
It says that the link(in the issue template) has been expired or I have no permission to join the chat. Moreover, I've been randomly kicked out of the chat several times.

**Comment by zeeshanlakhani** [comment]
I updated the one here: https://discord.gg/sAgzNV27sA. See if you're using that invite code. It shouldn't be temporary.

**Comment by zeeshanlakhani** [comment]
Thanks @drunkirishcoder for finding those. They all should be hitting that link I posted.
