### ISSUE TITLE
net_vdev_netvsc DPDK device not detected

### ISSUE THREAD

**Issue by mikebromwich** [capsule-rs/capsule#148]
I cannot get the net_vdev_netvsc0 device to be detected when trying to run the examples. 

I have the following port configuration:

[[ports]]
    name = "eth1"
    device = "net_vdev_netvsc0"
    args = "mac=00:15:5d:4e:52:06"
    cores = [0]

On starting the application, a debug message indicated that DPDK has recognized the device based on the device name:

net_vdev_netvsc: probably using routed NetVSC interface "eth1" (index 14)

However, in PortBuilder::new, the call to ffi::rte_eth_dev_get_port_by_name fails to find the device.

I am using the current Capsule version running in Ubuntu Ubuntu 20.04.2 LTS as a Virtual Machine under Hyper-V.

The DPDK command line tools (testpmd) work correctly with the device.

**Comment by zeeshanlakhani** [comment]
Thanks for opening this @mikebromwich. We def compile capsule with the poll mode driver: https://github.com/capsule-rs/capsule/blob/master/ffi/build.rs#L160. Maybe we can try to run this via an free Azure Linux instance, but haven't tested on that before.

**Comment by drunkirishcoder** [comment]
So I changed the config for the `skeleton` example to see if the driver is compiled and linked correctly for Capsule.

```
app_name = "skeleton"
master_core = 0
dpdk_args = "-v --log-level lib.eal:8"
duration = 5

[[ports]]
    name = "netvsc0"
    device = "net_vdev_netvsc0"
    args = "iface=eth0,force=1"
    cores = [0]
```

because I'm not running on Azure, I had to try with force binding just to see if DPDK can load the driver correctly. And it does. Here's the output,

```
net_vdev_netvsc: probably using routed NetVSC interface "eth0" (index 2)
EAL: request: eal_dev_mp_request
EAL: request: eal_dev_mp_request
net_vdev_netvsc: non-netvsc device was probed as netvsc
EAL: Module /sys/module/vfio not found! error 2 (No such file or directory)
Jan 21 02:11:36.037 DEBUG capsule::ffi::dpdk: EAL parsed 13 arguments.
Jan 21 02:11:36.038 DEBUG capsule::runtime: initializing mempool ...
EAL: Trying to obtain current memory policy.
EAL: Setting policy MPOL_PREFERRED for socket 0
EAL: Restoring previous memory policy: 0
EAL: request: mp_malloc_sync
EAL: Heap on socket 0 was expanded by 2MB
EAL: Trying to obtain current memory policy.
EAL: Setting policy MPOL_PREFERRED for socket 0
EAL: Restoring previous memory policy: 0
EAL: request: mp_malloc_sync
EAL: Heap on socket 0 was expanded by 150MB
Jan 21 02:11:36.065  INFO capsule::runtime::mempool: pool created. name="mempool"
```

So I don't think the problem is with driver linking. You can see from the log output, it found the device I pointed it to, and it even recognized it not being a netvsc, but force loaded the driver anyway.

I'm not sure what the problem is cuz I don't have access to Azure to test this out myself. Can you try use `iface` instead of `mac` and see if it can find the correct device?

**Comment by mikebromwich** [comment]
Thanks. I've tried using iface instead - with the same result. If I try to run the example whilst the NIC is still bound to the kernel, then I see an error message from within the netvsc code - so the driver is definitely being loaded. The call to ffi::rte_eal_init in eal_init succeeds and recognizes the name of the device. The problem only seems to be the subsequent call to ffi::rte_eth_dev_get_port_by_name which seems to fail to find it.

I'll build an entirely clean VM from scratch to check that it's not an environment problem.

**Comment by mikebromwich** [comment]
Building a new clean environment didn't fix the issue, but I have some more information.

I added some debug into rte_ethdev.c rte_eth_dev_get_port_by_name(...)  to show what ports are being considered at the second stage.

If I specify 'device=net_vdev_netvsc0' in the toml configuration file, the ports/devices which are then considered by DPDK are net_failsafe_vsc0 and net_tap_vsc0. Neither match, so it fails.

If I specify 'device=net_failsafe_vsc0' then the port/device it considers is 'net_failsafe_vsc0'. This matches - and it works. It does report the following errors - so perhaps this is just using the tap interface:

net_failsafe: Could not allocate sub_devices
net_failsafe: Could not allocate sub_devices
vdev_probe(): failed to initialize net_failsafe_vsc0 device


However, if I unbind the interfaces from the kernel (which I believe is the correct configuration)...

driverctl -v -b vmbus set-override {guid here} uio_hv_generic

...then when it considers ports/devices in rte_eth_dev_get_port_by_name(...), the names returned are the GUIDs - which therefore don't match and it doesn't work.

Unfortunately I don't know enough about the internals of DPDK to understand this - and in particular, how it relates to the explanation at [https://doc.dpdk.org/guides/nics/vdev_netvsc.html](https://doc.dpdk.org/guides/nics/vdev_netvsc.html)

**Comment by drunkirishcoder** [comment]
Yeah I have no knowledge of how netvsc works. looking at the doc and the [code](https://github.com/DPDK/dpdk/blob/main/drivers/net/vdev_netvsc/vdev_netvsc.c), it's quite different from the typical virtual PMDs we expect, that's usually a single device PMD and is named by the device name you provide. `netvsc` doesn't seem to [follow that pattern](https://github.com/DPDK/dpdk/blob/main/drivers/net/vdev_netvsc/vdev_netvsc.c#L600-L620), and that's likely why we can't locate the device generated.

**Comment by mikebromwich** [comment]
I think that the conclusion here is that the net_vnet_netvsc does not adhere to standard naming, so it is not feasible to support. I have worked around this by switching from Hyper-V to ESXi - so I'll close this issue.
